version: '3'

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile.my-app
    ports:
      - 4040:4040
      - 4200:4200
    volumes:
      - ./src:/app
    
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=toor4269
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  spark:
      build:
        context: .
        dockerfile: Dockerfile.spark
      environment:
        - SPARK_MODE=master
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
        - SPARK_USER=spark
      ports:
        - '8080:8080'
        - '7077:7077'
  spark-worker:
      build:
        context: .
        dockerfile: Dockerfile.spark
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark:7077
        - SPARK_WORKER_MEMORY=2G
        - SPARK_WORKER_CORES=2
        - SPARK_RPC_AUTHENTICATION_ENABLED=no
        - SPARK_RPC_ENCRYPTION_ENABLED=no
        - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
        - SPARK_SSL_ENABLED=no
        - SPARK_USER=spark
        - PYSPARK_PYTHON=./pyspark_pex_env.pex

volumes:
  minio-data: